# tensor操作方法
1.6版本

In [2]:
import torch

### 按照索引操作tensor
gather方法的作用，index代表索引位置，dim指定具体行还是列。比如以下例子[1,2,3;4,5,6]，指定dim=1，那么索引就是列号。index的大小就是输出的大小，比如index是[0,1;2,0]，那么看index第一行，0列指元素1，1列指元素2，同理，第二行为6，4，这样输出就为[1,2;6,4]，即可理解gather的含义。

gather在one-hot为输出的多分类问题中，可以把最大值坐标作为index传进去，然后提取到每一行的正确预测结果，这也是gather可能的一个作用。

torch.gather(input, dim, index, out=None)：在指定维度上按照索引赋值输出tensor。输入与输出大小一致。

torch.index_select(input, dim, index, out=None)：选出一维度的一些slice组合成新的tensor。指定维度的大小与index大小一致。

torch.masked_select(input, mask, out=None)：按照mask输出一个一维的tensor。

torch.take(input, indices)：将输入看成1D tensor，按照索引得到输出。输出大小与index大小一致。

torch.nonzero(input, out=None)：输出非0 元素的坐标。

torch.where(condition, x, y)：按照条件从x和y中选出满足条件的元素组成新的tensor。

In [10]:
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(b)
index_1 = torch.tensor([[0, 1], [2, 0]], dtype=torch.long)
index_2 = torch.tensor([[0, 1, 1], [0, 0, 0]], dtype=torch.long)
print(torch.gather(b, dim=1, index=index_1))
print(torch.gather(b, dim=0, index=index_2))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [6, 4]])
tensor([[1, 5, 6],
        [1, 2, 3]])


### 张量镜像翻转torch.flip
按照给定维度翻转张量

In [14]:
x = torch.arange(8).view(2, 2, 2)
print(x)
print(torch.flip(x, [2]))
print(torch.flip(x, [0, 1]))
print(torch.flip(x,[1,2]))

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
tensor([[[1, 0],
         [3, 2]],

        [[5, 4],
         [7, 6]]])
tensor([[[6, 7],
         [4, 5]],

        [[2, 3],
         [0, 1]]])
tensor([[[3, 2],
         [1, 0]],

        [[7, 6],
         [5, 4]]])


### 张量打平torch.flatten
假设t的形状是：(2,4,3,5,6)，则torch.flatten(t, 1, 3).shape 的结果为 (2, 60, 6)。

将索引为 start_dim 和 end_dim 之间（包括该位置）的数量相乘，其余位置不变。

因为默认 start_dim=0，end_dim=-1，所以 torch.flatten(t) 返回只有一维的数据。

In [7]:
x = torch.randn(2,4,3,5,6)
print(x.shape)
print(torch.flatten(x, 1, 3).shape)
print(torch.flatten(x).shape)

torch.Size([2, 4, 3, 5, 6])
torch.Size([2, 60, 6])
torch.Size([720])


### 张量拼接torch.cat
在指定的维度dim上对tensor序列进行连接操作，按照已经存在的维度进行。

torch.stack(seq, dim=0, out=None)：按照新的维度进行concatenate，它会增加一个维度。

In [15]:
x = torch.randn(2, 3)
print(x)
print(torch.cat((x, x), 0))
print(torch.cat((x, x), 1))

tensor([[-0.3645, -1.8158,  0.2189],
        [-1.0904, -0.7776,  1.1962]])
tensor([[-0.3645, -1.8158,  0.2189],
        [-1.0904, -0.7776,  1.1962],
        [-0.3645, -1.8158,  0.2189],
        [-1.0904, -0.7776,  1.1962]])
tensor([[-0.3645, -1.8158,  0.2189, -0.3645, -1.8158,  0.2189],
        [-1.0904, -0.7776,  1.1962, -1.0904, -0.7776,  1.1962]])


### 扩大张量torch.Tensor.expand
返回张量的一个新视图，可以将张量的单个维度扩大为更大的尺寸。

张量也可以扩大为更高维，新增加的维度将附在前面。扩大张量不需要分配新内存，仅仅是新建一个张量的视图。任意一个一维张量在不分配新内存情况下都可以扩展为任意的维度。

传入-1则意味着维度扩大不涉及这个维度。

In [29]:
x = torch.tensor([[1], [2], [3]])
print(x)
y = x.expand(3, 4)
print(y)

tensor([[1],
        [2],
        [3]])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])


### 张量压缩torch.squeeze
去除张量中数值为1的维度，并返回新的张量。

当通过dim参数指定维度时，维度压缩操作只会在指定的维度上进行。

如果一个张量只有1个维度，那么它不会受到上述方法的影响。

输出的张量与原张量共享内存，如果改变其中的一个，另一个也会改变。

In [26]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
y = torch.squeeze(x, 0)
print(y.size())
y = torch.squeeze(x, 1)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


### 重复张量torch.Tensor.repeat
沿着指定的维度重复张量。不同于expand()方法，本函数复制的是张量中的数据。

In [30]:
x = torch.Tensor([1, 2, 3])
print(x.repeat(4, 2))

tensor([[1., 2., 3., 1., 2., 3.],
        [1., 2., 3., 1., 2., 3.],
        [1., 2., 3., 1., 2., 3.],
        [1., 2., 3., 1., 2., 3.]])


### 缩小张量 torch.Tensor.narrow
返回一个经过缩小后的张量，操作的维度由dimension指定。

缩小范围是从start开始到start+length，执行本方法的张量与返回的张量共享相同的底层内存。

In [18]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x.narrow(0, 0, 2))
print(x.narrow(1, 1, 2))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])


### 张量变形 torch.Tensor.view
返回一个有相同数据但是不同形状的新的张量。

返回的张量必须与原张量有相同的数据和相同的元素个数，但是可以有不同的尺寸。

In [19]:
x = torch.randn(4, 4)
print(x.size())
y = x.view(16)
print(y.size())

torch.Size([4, 4])
torch.Size([16])


### 重设张量尺寸torch.Tensor.resize_
将张量的尺寸调整为指定的大小。如果元素个数比当前的内存大小大，就将底层存储大小调整为与新元素数目一致的大小。

如果元素个数比当前内存小，则底层存储不会被改变。原来张量中被保存下来的元素将保持不变，但新内存将不会被初始化。

In [23]:
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(x)
x.resize_(3, 2)
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


### 置换张量维度torch.Tensor.permute
将执行本方法的张量的维度换位。

In [24]:
x = torch.randn(2, 3, 5)
print(x.size())
print(x.permute(2, 0, 1).size())

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


### 查看张量单个元素的字节数 torch.Tensor.element_size
查看某类型张量单个元素的字节数。

In [25]:
torch.FloatTensor().element_size()

4